### ISSUE TITLE
テストが動かない

### ISSUE THREAD

**Issue by ymlaedr** [ymlaedr/rot_raven#33]
liveviewコンテナで`mix test`を流してみたら、こけた
```log
19:37:01.936 [error] GenServer #PID<0.4185.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (Mix) The database for RotRaven.Repo couldn't be created: killed
```

試しに下記も流すも、同じくエラー
```sh
MIX_ENV="test" mix do ecto.drop, ecto.create, ecto.migrate
```
```log
19:38:21.135 [error] GenServer #PID<0.227.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (Mix) The database for RotRaven.Repo couldn't be dropped: killed
```

**Comment by ymlaedr** [comment]
#35 で解決済みのためクローズ
